### ISSUE TITLE
fix intermittent test failure in 1.8.7 c9-payload-encryption-client-to-mesh.js

### ISSUE THREAD

**Issue by JensEggers** [happner/happner#128]
e.g. in 7b3828d0761d2513f560c8a3c8d32133e4423529:
```
~/git/happner (master)$ time mocha test/c9-payload-encryption-client-to-mesh.js 

 c9-payload-encryption-client-to-mesh
[ INFO] - 28ms	(HappnServer) crypto service loaded.
[ INFO] - 54ms	(HappnServer) data service loaded.
[ INFO] - 9ms	(System) instance name: brindlethunder_4JWyLXvnr-
[ INFO] - 0ms	brindlethunder_4JWyLXvnr- (HappnServer) system service loaded.
[ INFO] - 83ms	brindlethunder_4JWyLXvnr- (HappnServer) security service loaded.
[ INFO] - 103ms	brindlethunder_4JWyLXvnr- (HappnServer) pubsub service loaded.
[ INFO] - 1ms	brindlethunder_4JWyLXvnr- (HappnServer) listening at 0.0.0.0:54545
[ INFO] - 1ms	brindlethunder_4JWyLXvnr- (HappnServer) happn version 2.6.5
[ INFO] - 40ms	brindlethunder_4JWyLXvnr- (Mesh) home /home/jens/git/happner/test
[ INFO] - 1ms	brindlethunder_4JWyLXvnr- (Mesh) happner v1.8.6
[ INFO] - 0ms	brindlethunder_4JWyLXvnr- (Mesh) config v..
[ INFO] - 0ms	brindlethunder_4JWyLXvnr- (Mesh) localnode 'brindlethunder_4JWyLXvnr-' at pid 11158
[ INFO] - 262ms	brindlethunder_4JWyLXvnr- (Mesh) initialized!
[ INFO] - 6ms	brindlethunder_4JWyLXvnr- (Mesh) started component 'security'
[ INFO] - 0ms	brindlethunder_4JWyLXvnr- (Mesh) started component 'system'
[ INFO] - 1ms	brindlethunder_4JWyLXvnr- (Mesh) started!
benchmarket error: config specified requireGC, use --expose-gc
    ✓ server can call more than one method in sequence (callback)
[ INFO] - 15ms	brindlethunder_4JWyLXvnr- (HappnServer) released 0.0.0.0:54545
[ INFO] - 0ms	brindlethunder_4JWyLXvnr- (Mesh) stopped!
[ INFO] - 3ms	(HappnServer) crypto service loaded.
[ INFO] - 2ms	(HappnServer) data service loaded.
[ INFO] - 2ms	(System) instance name: mazedragon_NJI1UQv2Sb
[ INFO] - 0ms	mazedragon_NJI1UQv2Sb (HappnServer) system service loaded.
[ INFO] - 54ms	mazedragon_NJI1UQv2Sb (HappnServer) security service loaded.
[ INFO] - 7ms	mazedragon_NJI1UQv2Sb (HappnServer) pubsub service loaded.
[ INFO] - 0ms	mazedragon_NJI1UQv2Sb (HappnServer) listening at 0.0.0.0:54545
[ INFO] - 1ms	mazedragon_NJI1UQv2Sb (HappnServer) happn version 2.6.5
[ INFO] - 34ms	mazedragon_NJI1UQv2Sb (Mesh) home /home/jens/git/happner/test
[ INFO] - 0ms	mazedragon_NJI1UQv2Sb (Mesh) happner v1.8.6
[ INFO] - 0ms	mazedragon_NJI1UQv2Sb (Mesh) config v..
[ INFO] - 1ms	mazedragon_NJI1UQv2Sb (Mesh) localnode 'mazedragon_NJI1UQv2Sb' at pid 11158
[ INFO] - 182ms	mazedragon_NJI1UQv2Sb (Mesh) initialized!
[ INFO] - 3ms	mazedragon_NJI1UQv2Sb (Mesh) started component 'security'
[ INFO] - 0ms	mazedragon_NJI1UQv2Sb (Mesh) started component 'system'
[ INFO] - 0ms	mazedragon_NJI1UQv2Sb (Mesh) started!
    ✓ server can call more than one method in sequence (promise)
[ INFO] - 6ms	mazedragon_NJI1UQv2Sb (HappnServer) released 0.0.0.0:54545
[ INFO] - 0ms	mazedragon_NJI1UQv2Sb (Mesh) stopped!
[ INFO] - 2ms	(HappnServer) crypto service loaded.
[ INFO] - 4ms	(HappnServer) data service loaded.
[ INFO] - 1ms	(System) instance name: veilllama_4yoJLXPnS-
[ INFO] - 0ms	veilllama_4yoJLXPnS- (HappnServer) system service loaded.
[ INFO] - 60ms	veilllama_4yoJLXPnS- (HappnServer) security service loaded.
[ INFO] - 8ms	veilllama_4yoJLXPnS- (HappnServer) pubsub service loaded.
[ INFO] - 1ms	veilllama_4yoJLXPnS- (HappnServer) listening at 0.0.0.0:54545
[ INFO] - 0ms	veilllama_4yoJLXPnS- (HappnServer) happn version 2.6.5
[ INFO] - 39ms	veilllama_4yoJLXPnS- (Mesh) home /home/jens/git/happner/test
[ INFO] - 1ms	veilllama_4yoJLXPnS- (Mesh) happner v1.8.6
[ INFO] - 0ms	veilllama_4yoJLXPnS- (Mesh) config v..
[ INFO] - 0ms	veilllama_4yoJLXPnS- (Mesh) localnode 'veilllama_4yoJLXPnS-' at pid 11158
[ INFO] - 185ms	veilllama_4yoJLXPnS- (Mesh) initialized!
[ INFO] - 4ms	veilllama_4yoJLXPnS- (Mesh) started component 'security'
[ INFO] - 0ms	veilllama_4yoJLXPnS- (Mesh) started component 'system'
[ INFO] - 0ms	veilllama_4yoJLXPnS- (Mesh) started!
    ✓ server can listen for an event - then recieve an event by calling a method
[ INFO] - 6ms	veilllama_4yoJLXPnS- (HappnServer) released 0.0.0.0:54545
[ INFO] - 0ms	veilllama_4yoJLXPnS- (Mesh) stopped!
[ INFO] - 3ms	(HappnServer) crypto service loaded.
[ INFO] - 3ms	(HappnServer) data service loaded.
[ INFO] - 1ms	(System) instance name: cottonhound_VJ7eIQwhSb
[ INFO] - 0ms	cottonhound_VJ7eIQwhSb (HappnServer) system service loaded.
[ INFO] - 45ms	cottonhound_VJ7eIQwhSb (HappnServer) security service loaded.
[ INFO] - 8ms	cottonhound_VJ7eIQwhSb (HappnServer) pubsub service loaded.
[ INFO] - 1ms	cottonhound_VJ7eIQwhSb (HappnServer) listening at 0.0.0.0:54545
[ INFO] - 0ms	cottonhound_VJ7eIQwhSb (HappnServer) happn version 2.6.5
[ INFO] - 43ms	cottonhound_VJ7eIQwhSb (Mesh) home /home/jens/git/happner/test
[ INFO] - 0ms	cottonhound_VJ7eIQwhSb (Mesh) happner v1.8.6
[ INFO] - 1ms	cottonhound_VJ7eIQwhSb (Mesh) config v..
[ INFO] - 0ms	cottonhound_VJ7eIQwhSb (Mesh) localnode 'cottonhound_VJ7eIQwhSb' at pid 11158
[ INFO] - 189ms	cottonhound_VJ7eIQwhSb (Mesh) initialized!
[ INFO] - 3ms	cottonhound_VJ7eIQwhSb (Mesh) started component 'security'
[ INFO] - 0ms	cottonhound_VJ7eIQwhSb (Mesh) started component 'system'
[ INFO] - 0ms	cottonhound_VJ7eIQwhSb (Mesh) started!
[ INFO] - 226ms	client (MeshClient) initialized!
    ✓ client can call more than one method in sequence (callback) (237ms)
[ INFO] - 16ms	cottonhound_VJ7eIQwhSb (HappnServer) released 0.0.0.0:54545
[ INFO] - 0ms	cottonhound_VJ7eIQwhSb (Mesh) stopped!
[ INFO] - 2ms	(HappnServer) crypto service loaded.
[ INFO] - 2ms	(HappnServer) data service loaded.
[ INFO] - 1ms	(System) instance name: obsidiandive_Ek9x87D3rZ
[ INFO] - 0ms	obsidiandive_Ek9x87D3rZ (HappnServer) system service loaded.
[ INFO] - 34ms	obsidiandive_Ek9x87D3rZ (HappnServer) security service loaded.
[ INFO] - 3ms	obsidiandive_Ek9x87D3rZ (HappnServer) pubsub service loaded.
[ INFO] - 1ms	obsidiandive_Ek9x87D3rZ (HappnServer) listening at 0.0.0.0:54545
[ INFO] - 0ms	obsidiandive_Ek9x87D3rZ (HappnServer) happn version 2.6.5
[ INFO] - 29ms	obsidiandive_Ek9x87D3rZ (Mesh) home /home/jens/git/happner/test
[ INFO] - 0ms	obsidiandive_Ek9x87D3rZ (Mesh) happner v1.8.6
[ INFO] - 0ms	obsidiandive_Ek9x87D3rZ (Mesh) config v..
[ INFO] - 0ms	obsidiandive_Ek9x87D3rZ (Mesh) localnode 'obsidiandive_Ek9x87D3rZ' at pid 11158
[ INFO] - 151ms	obsidiandive_Ek9x87D3rZ (Mesh) initialized!
[ INFO] - 3ms	obsidiandive_Ek9x87D3rZ (Mesh) started component 'security'
[ INFO] - 0ms	obsidiandive_Ek9x87D3rZ (Mesh) started component 'system'
[ INFO] - 0ms	obsidiandive_Ek9x87D3rZ (Mesh) started!
[ INFO] - 187ms	client (MeshClient) initialized!
    ✓ client can call more than one method in sequence (promise) (199ms)
[ INFO] - 17ms	obsidiandive_Ek9x87D3rZ (HappnServer) released 0.0.0.0:54545
[ INFO] - 0ms	obsidiandive_Ek9x87D3rZ (Mesh) stopped!
[ INFO] - 2ms	(HappnServer) crypto service loaded.
[ INFO] - 3ms	(HappnServer) data service loaded.
[ INFO] - 2ms	(System) instance name: snowneck_EJX-UmvhBb
[ INFO] - 0ms	snowneck_EJX-UmvhBb (HappnServer) system service loaded.
[ INFO] - 52ms	snowneck_EJX-UmvhBb (HappnServer) security service loaded.
[ INFO] - 7ms	snowneck_EJX-UmvhBb (HappnServer) pubsub service loaded.
[ INFO] - 0ms	snowneck_EJX-UmvhBb (HappnServer) listening at 0.0.0.0:54545
[ INFO] - 1ms	snowneck_EJX-UmvhBb (HappnServer) happn version 2.6.5
[ INFO] - 66ms	snowneck_EJX-UmvhBb (Mesh) home /home/jens/git/happner/test
[ INFO] - 0ms	snowneck_EJX-UmvhBb (Mesh) happner v1.8.6
[ INFO] - 0ms	snowneck_EJX-UmvhBb (Mesh) config v..
[ INFO] - 0ms	snowneck_EJX-UmvhBb (Mesh) localnode 'snowneck_EJX-UmvhBb' at pid 11158
    1) "before each" hook
[FATAL] - 69ms	brindlethunder_4JWyLXvnr- (Mesh) uncaughtException (or set NO_EXIT_ON_UNCAUGHT) { [TypeError: Cannot read property 'description' of undefined] uncaught: true }
[FATAL] - TypeError: Cannot read property 'description' of undefined
    at HappnClient.client.data.on.deprecatedDestroyComponentsWarned (lib/system/shared/mesh-client.js:407:47)
    at HappnClient.delegate_handover (node_modules/happn/lib/client/base.js:691:22)
    at HappnClient.handle_data (node_modules/happn/lib/client/base.js:702:22)
    at HappnClient.handle_publication (node_modules/happn/lib/client/base.js:604:19)
    at done (primus.js:2239:48)
    at transform (primus.js:2210:30)
    at Primus.transforms (primus.js:2231:4)
    at decoding (primus.js:2008:14)
    at Primus.decoder (primus.js:2823:3)
    at Primus.message (primus.js:1997:12)
    at next (primus.js:140:17)
    at defer [as _onTimeout] (primus.js:2772:9)
[ INFO] - 0ms	brindlethunder_4JWyLXvnr- (Mesh) exit 1
[ INFO] - 0ms	mazedragon_NJI1UQv2Sb (Mesh) exit 1
[ INFO] - 0ms	veilllama_4yoJLXPnS- (Mesh) exit 1
[ INFO] - 0ms	cottonhound_VJ7eIQwhSb (Mesh) exit 1
[ INFO] - 0ms	obsidiandive_Ek9x87D3rZ (Mesh) exit 1
[ INFO] - 0ms	snowneck_EJX-UmvhBb (Mesh) exit 1

real	0m3.119s
user	0m3.108s
sys	0m0.100s
```

**Comment by JensEggers** [comment]
all the meshes are still alive at the end.

Could be related to #110 - leaked process.on() subscriptions
