### ISSUE TITLE
'Unhandled rejection Error' on an exchange call timeout

### ISSUE THREAD

**Issue by HaroldStruwig** [happner/happner#168]
it also only seems to happen when I make use of the shared data component (although the exchange call is not on the shared data component)

stacktrace:
```
Unhandled rejection Error: Request timed out
  at Object.ensureErrorObject (/node_js/app/node_modules/bluebird/js/main/util.js:261:20)
  at Promise._rejectCallback (/node_js/app/node_modules/bluebird/js/main/promise.js:469:22)
  at /node_js/app/node_modules/bluebird/js/main/promise.js:486:17
  at Object.handler (/node_js/app/node_modules/happner/lib/system/shared/promisify.js:30:29)
  at Object.<anonymous> (/node_js/app/node_modules/happner/lib/system/shared/messenger.js:345:19)
  at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

**Comment by HaroldStruwig** [comment]
the exchange call originates from the frontend
