### ISSUE TITLE
1.17.0 [FATAL] uncaught exception mesh-client.js:407

### ISSUE THREAD

**Issue by JensEggers** [happner/happner#172]
```
[FATAL] - 16ms	Vym3n3UHKW (Mesh) uncaughtException (or set NO_EXIT_ON_UNCAUGHT) { [TypeError: Cannot read property 'description' of undefined] uncaught: true }
[FATAL] - TypeError: Cannot read property 'description' of undefined
    at HappnClient.client.data.on.deprecatedDestroyComponentsWarned (node_modules/happner/lib/system/shared/mesh-client.js:407:47)
    at HappnClient.delegate_handover (node_modules/happn/lib/client/base.js:792:22)
    at HappnClient.handle_data (node_modules/happn/lib/client/base.js:803:22)
    at HappnClient.handle_publication (node_modules/happn/lib/client/base.js:711:19)
    at done (primus.js:2239:48)
    at transform (primus.js:2210:30)
    at Primus.transforms (primus.js:2231:4)
    at decoding (primus.js:2008:14)
    at Primus.decoder (primus.js:2823:3)
    at Primus.message (primus.js:1997:12)
    at next (primus.js:140:17)
    at defer [as _onTimeout] (primus.js:2772:9)

**Comment by JensEggers** [comment]
test log is here:
https://travis-ci.com/FieldServer/device-registration-components/jobs/47542093

**Comment by JensEggers** [comment]
another log:
https://travis-ci.com/FieldServer/device-registration-components/jobs/47549963
