### ISSUE TITLE
Missing 'id' property error in function call across newly reconnected secure exchange

### ISSUE THREAD

**Issue by nomilous** [happner/happner#179]
When a secure mesh (1) has an endpoint to secure mesh (2) and 2 is restarted such that the endpoint from 1 is disconnected for a period.

If within mesh 1 there is an interval timer repeating a call across the exchange, while the endpoint is offline the expected 'request timed out' error is returned. But once the endpoint recovers the first next call results in the error below. Subsequent calls then begin to succeed.

[ERROR] - TypeError: Cannot read property 'id' of undefined
    at HappnClient.handle_publication (/git/tls-tunnel-service/node_modules/happn/lib/client/base.js:721:15)
    at Primus.emit (events.js:98:17)
    at done (primus.js:2239:48)
    at transform (primus.js:2210:30)
    at Primus.transforms (primus.js:2231:4)
    at decoding (primus.js:2008:14)
    at Primus.decoder (primus.js:2823:3)
    at Primus.message (primus.js:1997:12)
    at Primus.emit (events.js:95:17)
    at next (primus.js:140:17)
    at defer [as _onTimeout] (primus.js:2772:9)
    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)

**Comment by JensEggers** [comment]
this is the likely culprit (socket.session is undefined):
```
PubSubService.prototype.authorizeRequest = function (socket, message, callback) {
  var _this = this;

  if (_this.trusted[socket.session.id] == undefined) return _this.handleDataResponseSocket(_this.securityService.AccessDeniedError('connection untrusted'), message, null, socket);

  if (message.action == 'off') return callback();//you dont need permission to stop listening

  _this.securityService.authorize(socket.session, message.path.replace(/^\/(?:REMOVE|SET|ALL)@/, ''), message.action, function (e, authorized, reason) {

    if (e) return _this.handleDataResponseSocket(e, message, null, socket);
    if (!authorized) return _this.handleDataResponseSocket(_this.securityService.AccessDeniedError('unauthorized', reason), message, null, socket);

    callback();
  });
};
```
