### ISSUE TITLE
Windows/mocha: Error: Resolution method is overspecified. Specify a callback *or* return a Promise; not both.

### ISSUE THREAD

**Issue by JensEggers** [happner/happner#223]
```
 1) e8-security-meshclient.js "after all" hook: stop server:
    Error: Resolution method is overspecified. Specify a callback *or* return a Promise; not both.
     at C:\Users\VM_USER\AppData\Roaming\nvm\v0.10.46\node_modules\mocha\lib\runnable.js:369:21
     at E:\git\happner\lib\mesh.js:807:21
     at E:\git\happner\node_modules\happn\lib\service.js:198:15
     at E:\git\happner\node_modules\happn\node_modules\async\lib\async.js:52:16
     at E:\git\happner\node_modules\happn\node_modules\async\lib\async.js:269:32
     at E:\git\happner\node_modules\happn\node_modules\async\lib\async.js:44:16
     at E:\git\happner\node_modules\happn\lib\services\pubsub\service.js:76:11
     at done (E:\git\happner\node_modules\primus\index.js:993:13)
     at Primus.asyncemit (E:\git\happner\node_modules\asyncemit\index.js:37:26)
     at Primus.close (E:\git\happner\node_modules\primus\index.js:950:10)
     at Server.closed (E:\git\happner\node_modules\primus\index.js:922:18)
     at net.js:1277:10

**Comment by JensEggers** [comment]
search tests for 'issue 223'
