### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by JensEggers** [happner/happner#297]
```
/node_modules/happner/lib/system/datalayer.js:291
      store.server.services.pubsub.on('disconnect', function (ev) {
                                  ^

TypeError: Cannot read property 'on' of undefined
    at Object.__done (/home/jens/git/open-sdk-sample-app/node_modules/happner/lib/system/datalayer.js:291:35)
    at Server.<anonymous> (/home/jens/git/open-sdk-sample-app/node_modules/happner/node_modules/happn/lib/service.js:274:23)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:185:7)
    at emitListeningNT (net.js:1284:10)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

Process finished with exit code 1
```

**Comment by JensEggers** [comment]
working on minimal config to trigger this
