### ISSUE TITLE
bug with new templating permissions on nedb

### ISSUE THREAD

**Issue by JensEggers** [happner/happner#318]
It looks like whenever the database is compacted (or maybe written to file?) we get an error that the key can't contain a .

```
2018-10-05 10:13:56.198 [FATAL] - 3752ms    (Mesh) uncaughtException (or set NO_EXIT_ON_UNCAUGHT) { Error: Field names cannot contain a .
  at checkKey (node_modules/happn-nedb/lib/model.js:37:11)
  at Object.<anonymous> (node_modules/happn-nedb/lib/model.js:74:5)
  at JSON.stringify (<anonymous>)
  at Object.serialize (node_modules/happn-nedb/lib/model.js:73:14)
  at node_modules/happn-nedb/lib/persistence.js:129:48
  at Array.forEach (<anonymous>)
  at Persistence.persistCachedDatabase (node_modules/happn-nedb/lib/persistence.js:128:24)
  at node_modules/happn-nedb/lib/executor.js:40:13
  at Immediate.process [as _onImmediate] (node_modules/happn-nedb/node_modules/async/lib/async.js:731:21) uncaught: true }
```

**Comment by southbite** [comment]
This is also in old happner, wrong project
