### ISSUE TITLE
Default config ($happner) with persistent routes with persist false throws

### ISSUE THREAD

**Issue by JohanvdWest** [happner/happner#54]
When defining a $happner for persistent routes without specifying persist:true in the mesh config, the mesh throws an exception:

```
Cannot read property 'persist' of undefined
    at DataEmbeddedService.addDataStoreFilter (D:\git\email-component\node_modules\happner\node_modules\happn\lib\services\data_embedded\service.js:118:37)
    at Mesh.<anonymous> (D:\git\email-component\node_modules\happner\lib\mesh.js:1288:49)
    at D:\git\email-component\node_modules\happner\lib\mesh.js:1321:7
    at D:\git\email-component\node_modules\happner\lib\system\componentInstance.js:726:7
    at D:\git\email-component\node_modules\happner\node_modules\happn\lib\client\plugins\intra-process.js:219:5
    at HappnClient._this.authorizeRequest (D:\git\email-component\node_modules\happner\node_modules\happn\lib\client\plugins\intra-process.js:35:6)
    at HappnClient.module.exports.on (D:\git\email-component\node_modules\happner\node_modules\happn\lib\client\plugins\intra-process.js:207:9)
    at HappnClient.tryCatcher (D:\git\email-component\node_modules\happner\node_modules\bluebird\js\main\util.js:26:23)
    at HappnClient.ret (eval at <anonymous> (D:\git\email-component\node_modules\happner\node_modules\bluebird\js\main\promisify.js:163:12), <anonymous>:24:28)
    at ComponentInstance._attach (D:\git\email-component\node_modules\happner\lib\system\componentInstance.js:633:13)
    at ComponentInstance.initialize (D:\git\email-component\node_modules\happner\lib\system\componentInstance.js:185:10)
    at Mesh._createComponent (D:\git\email-component\node_modules\happner\lib\mesh.js:1312:21)
    at async.series._this._eachComponentDo.methodCategory (D:\git\email-component\node_modules\happner\lib\mesh.js:953:13)
    at D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:607:21
    at D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:246:17
    at iterate (D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:146:13)
    at D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:157:25
    at D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:248:21
    at D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:612:34
    at Mesh._happnizeModule (D:\git\email-component\node_modules\happner\lib\mesh.js:1237:3)
    at async.series._this._eachComponentDo.methodCategory (D:\git\email-component\node_modules\happner\lib\mesh.js:950:13)
    at D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:607:21
    at D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:246:17
    at iterate (D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:146:13)
    at D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:157:25
    at D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:248:21
    at D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:612:34
    at Mesh._createModule (D:\git\email-component\node_modules\happner\lib\mesh.js:1212:12)
    at async.series._this._eachComponentDo.methodCategory (D:\git\email-component\node_modules\happner\lib\mesh.js:947:13)
    at D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:607:21
    at D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:246:17
    at iterate (D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:146:13)
    at async.eachSeries (D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:162:9)
    at _asyncMap (D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:245:13)
    at Object.mapSeries (D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:228:23)
    at Object.async.series (D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:605:19)
    at Mesh.<anonymous> (D:\git\email-component\node_modules\happner\lib\mesh.js:945:9)
    at Mesh.tryCatcher (D:\git\email-component\node_modules\happner\node_modules\bluebird\js\main\util.js:26:23)
    at Mesh.ret [as _createElement] (eval at <anonymous> (D:\git\email-component\node_modules\happner\node_modules\bluebird\js\main\promisify.js:163:12), <anonymous>:15:23)
    at D:\git\email-component\node_modules\happner\lib\mesh.js:793:22
    at D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:567:21
    at D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:246:17
    at D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:122:13
    at _each (D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:46:13)
    at async.each (D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:121:9)
    at _asyncMap (D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:245:13)
    at Object.map (D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:216:23)
    at _parallel (D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:565:20)
    at Object.async.parallel (D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:595:9)
    at Mesh._initializeElements (D:\git\email-component\node_modules\happner\lib\mesh.js:753:16)
    at async.series._this._mesh.initialized (D:\git\email-component\node_modules\happner\lib\mesh.js:429:15)
    at D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:607:21
    at D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:246:17
    at iterate (D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:146:13)
    at D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:157:25
    at D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:248:21
    at D:\git\email-component\node_modules\happner\node_modules\async\lib\async.js:612:34
    at D:\git\email-component\node_modules\happner\lib\system\api.js:1060:7
    at tryCatcher (D:\git\email-component\node_modules\happner\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (D:\git\email-component\node_modules\happner\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (D:\git\email-component\node_modules\happner\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (D:\git\email-component\node_modules\happner\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (D:\git\email-component\node_modules\happner\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (D:\git\email-component\node_modules\happner\node_modules\bluebird\js\main\async.js:133:10)
    at Async.drainQueues (D:\git\email-component\node_modules\happner\node_modules\bluebird\js\main\async.js:15:14)
    at process._tickCallback (node.js:448:13)
```

Example:
Component $happner object:
```
{
  config: {
    component: {
      startMethod: 'start',
      stopMethod: 'stop',
      data:{
        routes:{
          "transporterOptions":"persist",
          "recipientGroups/*":"persist",
          "retryOptions":"persist"
        }
      },
      schema: {
        exclusive: false
      }
    }
  }
};
```

**Comment by southbite** [comment]
Is this a high priority bug? Surely if you define routes that are persistent, you should be defining them in a mesh config with a filename or persist:true?

**Comment by JohanvdWest** [comment]
I agree that that is the case in a production environment, but it is not
always the case in an automatic testing environment.

I am working around it by specifying the file and deleting it before the
test, but my feeling is that you should not need a persistent store, even
if you have persistent paths.

Probably not a High Priority bug though.

**Comment by JensEggers** [comment]
Johan, I'm a bit confused by this - what do we expect the mesh to do with persistent paths if it is not persistent?

**Comment by JohanvdWest** [comment]
So the scenario is this, and perhaps I am thinking about it the wrong way, which would be good to clear up.

* I have a component that has in its default happner object it's persistent paths. It stores its own configuration data that is accessible using the API. (email component for information)
 * As always we do not want each person that uses this component to specify these paths as it is internal to this component, that is why it is on the default config.
 * I don't think we want each person that uses this to overwrite it if persistence is not required.
 * This component also has a test mode that other components can use to test their interface to it.
* Other components might not have persistent data, so none of the test configs has persist set to true. They include this component in their test configs to test the interface and the result.
 * Currently this will throw an exception that a persist is undefined somewhere in happner (it assumes that there will be a persistent store)
 * Even if this does not work, I believe that it should at worst give an error in the log, but not throw an unhandled exception.

For me the ideal solution is to always create the second data store (and call it persist), but only make it persistent if persist is set to true. This means all code is executed the same on the happn level, but we decide at config time if the db is stored to the disk or not.

**Comment by JensEggers** [comment]
I see Johan's point. Components that 'request' persistent paths should still work in a non-persistent mesh. We should at least print a warning where a component is not being given the persistent storage it 'requested', but it makes sense to then find a way to store the relevant paths in a non-persistent way.
