### ISSUE TITLE
System component getStats() returns un-encodable [Object]

### ISSUE THREAD

**Issue by nomilous** [happner/happner#84]
```

DATA::: { data: { status: 'ok', args: [ null, [Object] ] },
  _meta: 
   { path: '/_exchange/responses/a78b2196-5902-4c38-a8b7-efe2ce8c179c/CLIENT/system/getStats/1',
     type: 'data',
     status: 'ok',
     published: true,
     eventId: 10,
     sessionId: 'a78b2196-5902-4c38-a8b7-efe2ce8c179c',
     action: '/SET@/_exchange/responses/a78b2196-5902-4c38-a8b7-efe2ce8c179c/CLIENT/system/getStats/1',
     channel: '/SET@/_exchange/responses/a78b2196-5902-4c38-a8b7-efe2ce8c179c/*' } }


[ERROR] - 14ms	CLIENT (PubSub) socket error { [ParserError: Failed to encode outgoing data: Object #<Object> has no method 'getTime']
  message: 'Failed to encode outgoing data: Object #<Object> has no method \'getTime\'',
  name: 'ParserError' }
[ERROR] - ParserError: Failed to encode outgoing data: Object #<Object> has no method 'getTime'
    at encoded (/Users/nomilous/git/tunnel-service/node_modules/happner/node_modules/happn/node_modules/primus/spark.js:478:21)
    at Sparky.encoder (/Users/nomilous/git/tunnel-service/node_modules/happner/node_modules/happn/node_modules/primus/parsers/json.js:16:3)
    at Sparky._write (/Users/nomilous/git/tunnel-service/node_modules/happner/node_modules/happn/node_modules/primus/spark.js:470:18)
    at done (/Users/nomilous/git/tunnel-service/node_modules/happner/node_modules/happn/node_modules/primus/spark.js:379:16)
    at transform (/Users/nomilous/git/tunnel-service/node_modules/happner/node_modules/happn/node_modules/primus/spark.js:338:30)
    at finished (/Users/nomilous/git/tunnel-service/node_modules/happner/node_modules/happn/node_modules/primus/spark.js:357:7)
    at PubSubService.outgoingTransform (/Users/nomilous/git/tunnel-service/node_modules/happner/node_modules/happn/lib/services/pubsub/service.js:184:2)
    at transform (/Users/nomilous/git/tunnel-service/node_modules/happner/node_modules/happn/node_modules/primus/spark.js:353:17)
    at Sparky.transforms (/Users/nomilous/git/tunnel-service/node_modules/happner/node_modules/happn/node_modules/primus/spark.js:359:4)
    at Sparky.write (/Users/nomilous/git/tunnel-service/node_modules/happner/node_modules/happn/node_modules/primus/spark.js:443:8)
    at PubSubService.emitToAudience (/Users/nomilous/git/tunnel-service/node_modules/happner/node_modules/happn/lib/services/pubsub/service.js:651:35)
    at PubSubService.publish (/Users/nomilous/git/tunnel-service/node_modules/happner/node_modules/happn/lib/services/pubsub/service.js:680:9)
    at PubSubService.createResponse (/Users/nomilous/git/tunnel-service/node_modules/happner/node_modules/happn/lib/services/pubsub/service.js:229:9)
    at PubSubService.handleDataResponseLocal (/Users/nomilous/git/tunnel-service/node_modules/happner/node_modules/happn/lib/services/pubsub/service.js:292:27)
    at /Users/nomilous/git/tunnel-service/node_modules/happner/node_modules/happn/lib/client/plugins/intra-process.js:135:49
    at HappnClient._this.authorizeRequest (/Users/nomilous/git/tunnel-service/node_modules/happner/node_modules/happn/lib/client/plugins/intra-process.js:37:6)
    at HappnClient.module.exports.performRequest (/Users/nomilous/git/tunnel-service/node_modules/happner/node_modules/happn/lib/client/plugins/intra-process.js:132:8)
    at HappnClient.module.exports.setInternal (/Users/nomilous/git/tunnel-service/node_modules/happner/node_modules/happn/lib/client/plugins/intra-process.js:184:8)
    at Object.<anonymous> (/Users/nomilous/git/tunnel-service/node_modules/happner/node_modules/happn/lib/client/plugins/intra-process.js:180:10)
    at Object.immediate._onImmediate (timers.js:381:16)
    at processImmediate [as _immediateCallback] (timers.js:363:15)

```

Offending line https://github.com/happner/happner/blob/master/lib/modules/system/index.js#L90

```
statistics.timestamp = moment.utc();
```

**Comment by nomilous** [comment]
I don't know client libraries are using the complex moment.utc() [object]

ie. can it simply be change to the identical value Date.now() [number]
